<<<<<<< HEAD
=======
# Sample .travis.yml for R projects

>>>>>>> overpass/master
language: r
warnings_are_errors: true
sudo: required

<<<<<<< HEAD
r:
    #- devel
    - release

r_github_packages:
      - jimhester/covr

after_success:
      - Rscript -e 'covr::codecov()'
=======
env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change
>>>>>>> overpass/master
